### PR TITLE
redo sidebar network links

### LINKED ISSUE #1218: redo sidebar network links
image

### PR DESCRIPTION
**Pull request by nguyenoanh5597**
close #1218 

- redo sidebar network links
- fix bug highlight views page
- reduce gap of devices menu

image

### CODE REVIEW

**Comment by NubeDev** [comment]
@riteshakya037 
Can you please check/approve

**Comment by riteshakya037** [comment]
@nguyenoanh5597, I looked at the implementation and found one important element missing. We need a link to access the Networks Page, but it got removed when we took out the `Drivers` NavItem. Here's an example of how it should look:


Screenshot 2023-06-23 at 3 01 34 PM

**Review by riteshakya037 — CHANGES_REQUESTED** [review]
Please refer to above comment

**Comment by nguyenoanh5597** [comment]
> Please refer to above comment

As requirement, we will remove Drivers NavItem, and use the other `Divers` to access the Networks Page

redo networks links
image

**Comment by riteshakya037** [comment]
@nguyenoanh5597 The problem is we can't access the Networks page anymore, it just expands the NavItem. The functionality should be similar to how `Group1 (Devices)` and `Rc Update (Device)` works, where if you click on `(Devices)` and `(Device)`, it opens their respective pages on the right, but if you click anywhere else in the NavItem it expands/collapses it

**Comment by nguyenoanh5597** [comment]
@riteshakya037 actually we can, if you want to make the same as `Group1 (Devices)` or `Rc Update (Device)`, i can update it to `Drivers (Networks)`, and click `(Networks)` will navigate to Networks page

redo networks links

**Comment by nguyenoanh5597** [comment]
Updated 

access Networks page

**Comment by riteshakya037** [comment]
@nguyenoanh5597 Thanks, I must say I didn't notice that clicking on the actual name would navigate you to the Networks page. Nonetheless, we should keep the UX consistent.

**Review by riteshakya037 — APPROVED** [review]

**Pull request merged**
